name: Trigger Test 2

on:
  push:
  pull_request:

jobs:
  trigger-test:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Python
        run: |
          python3 ${GITHUB_WORKSPACE}/test.py
